### PR TITLE
Add option to combine multiple tilesets

### LINKED ISSUE #19: Provide utility to let client combine multiple converted tilesets together
Currently each dataset is converted into a separate tileset. We should provide a utility to let client combine them together into a single global tileset

### PR DESCRIPTION
**Pull request by baothientran**
Fixes #19 

Add new option to combine multiple tilesets into one. 
For example: To combine Elevation with component selectors 1_1 and GSModels with component selectors 2_1 into one, we can do like this:
```
--combine=Elevation_1_1,GSModels_2_1
```

You can repeat that option multiple times to group different local tilesets into different global tilesets. For example: To group Elevation and GSModels into one tileset and group all GTModels in different tileset, we can do:
```
--combine=Elevation_1_1,GSModels_2_1 --combine=GTModels_1_1,GTModels_2_1
```

With or without the option, the converter still groups each dataset from different GeoCells into a different global tileset for each dataset:

For example, if CDB has two GeoCells with coordinates (N32, W118) and (N32, W119), and each GeoCell has elevation and GSModels dataset, the tiler will combine all the elevation of all GeoCell into one global tileset for Elevation. Same with GSModels. Below is the new organization for global tilesets:

Screenshot_20201123_131852

### CODE REVIEW

**Comment by lilleyse** [comment]
The 3D Tiles Validator is picking up a small error:

```
slilley@Lithium:~/Code/3d-tiles-validator/validator$ node bin/3d-tiles-validator.js -i ~/Downloads/San_Diego/Elevation_1_1GSModels_1_1GTModels_1_1GTModels_2_1.json 
Tileset must declare its geometricError as a top-level property.
```

**Comment by baothientran** [comment]
@lilleyse I've updated the fix in the new commit

**Comment by baothientran** [comment]
@lilleyse I just realize I have an unused function `combineTilesetJson(const std::vector<std::filesystem::path> &tilesetJsonPaths, const Core::BoundingRegion &regions, std::ofstream &fs);`. This function was in TileFormatIO.h and TileFormatIO.cpp. This is now removed in the new commit

**Comment by lilleyse** [comment]
Overall, the way you've structured the tileset files makes a lot of sense. During testing I did have a few observations that I think could improve this PR.

* [ ] The converter will process all the datasets even if some of them will not be included in the combined tilesets. I think better behavior would be to only process those datasets that are needed. This will speed up processing time if someone is only concerned about one dataset.
* [ ] The converter should error out if you use a component selector that doesn't exist. E.g. `--combine Elevation_1_5`
* [ ] An invalid tileset is produced if only a single dataset is used like `--combine Elevation_1_1`. The tileset.json will refer to itself recursively.
* [ ] The relationship between elevation and imagery is a little unclear. I think elevation and imagery should both be supplied in `--combine` if you want to combine them into the same tileset. Someone may want to convert elevation without the imagery. However, the converter would need to print an error if imagery is converted and elevation is not.
* [ ] We should consider updating the [datasets table](https://github.com/CesiumGS/cdb-to-3dtiles/tree/tileset-combine#feature-checklist) in the README so that it follows the Datasets_CS1_CS2 format, that way it's easier to know what datasets can be combined together.
* [ ] If `--combined` is only supplied once or not supplied at all (e.g. _not_ `--combine=Elevation_1_1,GSModels_1_1 --combine=GTModels_2_1,GTModels_1_1`) then I think the tileset should be called `tileset.json` instead of, say, `Elevation_1_1GSModels_1_1GTModels_2_1GTModels_1_1.json` so it's very obvious that it's the root tileset.
* [ ] The tilesets in the geocell folders should no longer be called `tileset.json` and instead should follow a naming convention similar to the b3dm tiles.
* [ ] The minimum height and maximum height of the regions in the tileset JSON files all seem to be 0.0

**Comment by baothientran** [comment]
I've created issues for the remaining items: 
* [ ] The converter will process all the datasets even if some of them will not be included in the combined tilesets. I think better behavior would be to only process those datasets that are needed. This will speed up processing time if someone is only concerned about one dataset. (https://github.com/CesiumGS/cdb-to-3dtiles/issues/27)
* [ ] The converter should error out if you use a component selector that doesn't exist. E.g. `--combine Elevation_1_5` (https://github.com/CesiumGS/cdb-to-3dtiles/issues/37)
* [ ] We should consider updating the [datasets table](https://github.com/CesiumGS/cdb-to-3dtiles/tree/tileset-combine#feature-checklist) in the README so that it follows the Datasets_CS1_CS2 format, that way it's easier to know what datasets can be combined together. (https://github.com/CesiumGS/cdb-to-3dtiles/issues/37)
* [ ] The relationship between elevation and imagery is a little unclear. I think elevation and imagery should both be supplied in `--combine` if you want to combine them into the same tileset. Someone may want to convert elevation without the imagery. However, the converter would need to print an error if imagery is converted and elevation is not. (https://github.com/CesiumGS/cdb-to-3dtiles/issues/38)
* [ ] The minimum height and maximum height of the regions in the tileset JSON files all seem to be 0.0 (https://github.com/CesiumGS/cdb-to-3dtiles/issues/39)

**Comment by lilleyse** [comment]
Thanks for opening the issues @baothientran. I verified the fixes for everything that was checked off. I also ran the converter and loaded the tilesets in CesiumJS to confirm that nothing strange happened.

I briefly looked at the code, didn't have any comments.

**Pull request merged**
